# Generated by Django 5.0.6 on 2024-07-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GT', '0002_rename_name_service_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
